#!/bin/sh
. /etc/default/rcS
FB=fb0
while [ ! -e "/dev/${FB}" ]
do
	echo "No framebuffer, cannot start GUI"
	sleep 5
done
if [ "$ROOTFS_READ_ONLY" = "yes" ]
then
	export TSLIB_CALIBFILE=/tmp/pointercal
else
	export TSLIB_CALIBFILE=/etc/pointercal
fi
TS=/dev/input/touchscreen0
if grep -q '^connected' /sys/class/drm/card0-HDMI-A-1/status
then
	echo "External HDMI monitor connected."
	# Locate external screen
	for f in /sys/class/graphics/*
	do
		if ! grep -q 'vdma-fb' $f/name
		then
			# Disable the backlight of the local display
			echo 1 > /sys/class/backlight/backlight/bl_power
			# workaround for monitor not working at startup.
			echo -n > /dev/dri/controlD64
			FB=`basename $f`
			echo "Found external display at $FB"
			break
		fi
	done
	TS="No Touchscreen"
	for f in /sys/class/input/event*
	do
		if ! grep -q AD7879 $f/device/name
		then
			if grep -q "input:.*-e0.*,3,.*a0,1,\|ads7846" $f/device/modalias
			then
				b=`basename $f`
				TS=/dev/input/$b
				echo "Found external touch screen at $b"
				TSLIB_CALIBFILE=${TSLIB_CALIBFILE}.$b
				break
			fi
		fi
	done
else
	# Locate internal touchscreen
	for f in /sys/class/graphics/*
	do
		if grep -q 'vdma-fb' $f/name
		then
			FB=`basename $f`
			echo "Found vdma-fb at $FB"
			break
		fi
	done
	for d in /dev/input/event*
	do
		b=`basename $d`
		if grep -q AD7879 /sys/class/input/$b/device/name
		then
			echo "AD7879 found at $b"
			TS=$d
			TSLIB_CALIBFILE=${TSLIB_CALIBFILE}.$b
			break
		fi
	done
fi
for f in /sys/class/input/event*
do
        if grep -iq "Keyboard" $f/device/name
        then
                b=`basename $f`
                echo "Found Keyboard at $b"
                ln -s /dev/input/$b /dev/input/eventkeyboard
        fi
        if grep -iq "Headphone" $f/device/name
        then
                b=`basename $f`
                echo "Found Headphone at $b"
                ln -s /dev/input/$b /dev/input/eventheadphone
        fi
done

export TSLIB_FBDEVICE=/dev/${FB}
export FRAMEBUFFER=${TSLIB_FBDEVICE}
export QWS_DISPLAY="LinuxFb:/dev/${FB}"
if [ -e "${TS}" ]
then
	export TSLIB_TSDEVICE="${TS}"
	export QWS_MOUSE_PROTO="Tslib:${TS}"
	export POINTERCAL_FILE="${TSLIB_CALIBFILE}"
	if [ ! -e "${TSLIB_CALIBFILE}" ]
	then
		ts_calibrate
		sync
	fi
fi
exec startxfce4
